# main-deploy.yml

name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  REACT_APP_NEWS_API_KEY: ${{secrets.REACT_APP_NEWS_API_KEY}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: 'test'

        run: echo "Commit id => $REACT_APP_NEWS_API_KEY"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://baekstodo
